---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-core
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      containers:
      - image: grafana/grafana:4.4.3
        name: grafana-core
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
          # Defaults to Viewer, other valid options are Editor and Admin.
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Viewer
          # does not really work, because of template variables in exported dashboards:
          - name: GF_DASHBOARDS_JSON_ENABLED
            value: "true"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana
    component: core
